import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/header";
import ScriptEditor from "../components/ScriptEditor";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Script editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ScriptEditor />
    </div>
  )
}
